server:
  port: 8082
spring:
  main:
    banner-mode: off
  application:
    name: service-notification
  config:
    import: "configserver:http://service-main:8888/config"
  cloud:
    config:
      uri: "http://service-main:8888/config"

eureka:
  client:
    serviceUrl:
      defaultZone: "http://service-main:8888/eureka"
  instance:
    prefer-ip-address: false
    hostname: service-notification