server:
  port: 8888

spring:
  main:
    banner-mode: off
  application:
    name: service-tasks
  cloud:
    config:
      server:
        prefix: "/config"
        git:
          uri: https://github.com/erickknsilva/config-server.git
          clone-on-start: true
          search-paths: config
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    hostname: localhost
  server:
    self-preservation: false
    lease-renewal-interval-in-seconds: 30  # Renovação a cada 30 segundos
    lease-expiration-duration-in-seconds: 90